Repository DASOM-GitHub/dasom-web-backend, pull requests merged in 2025-03, with the labels that each got.

#58 [fix] 면접 예약 API 조회 기능 추가
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewService.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
Labels: FIX

#60 [fix] 면접 예약 API 면접 일정 조회시 status도 같이 반환
  src/main/java/dmu/dasom/api/domain/interview/dto/InterviewSlotResponseDto.java
Labels: FIX

#61 [fix] 면접 예약 API 예약자 명단 조회 API 추가
  src/main/java/dmu/dasom/api/domain/interview/dto/InterviewReservationApplicantResponseDto.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewService.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
Labels: FIX

#62 [fix] 면접 예약자 조회 API 면접일, 면접시간, 면접을 예약한 날짜와 시간 추가
  src/main/java/dmu/dasom/api/domain/interview/dto/InterviewReservationApplicantResponseDto.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
Labels: FIX

#57 [docs] 리드미 꾸미기
  LICENSE
  README.md
Labels: DOCS

#65 [fix] 부원 모집 로직; 모집 일정 검증 추가
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
  src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
Labels: FIX

#70 [infra] CI/CD 캐싱 도입
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
Labels: INFRA
