Repository DASOM-GitHub/dasom-web-backend, pull requests merged in 2025-02, with the labels that each got.

#4 [infra] 커스텀 예외 구성
  src/main/java/dmu/dasom/api/domain/common/exception/CustomControllerAdvice.java
  src/main/java/dmu/dasom/api/domain/common/exception/CustomException.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorResponse.java
Labels: infra

#6 [infra] CI/CD 파이프라인 구축
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
  Dockerfile
  build.gradle
  src/main/resources/application-credentials.yml
  src/main/resources/application.yml
Labels: infra

#7 [fix] 컨테이너 포트 개방 옵션 추가
  Dockerfile
Labels: fix

#10 [fix] 블랙리스트 토큰 저장 방식 수정
  src/main/java/dmu/dasom/api/global/auth/jwt/JwtUtil.java
Labels: fix

#16 [feat] Applicant 도메인 구현
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantCreateRequestDto.java
  src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
  src/main/java/dmu/dasom/api/domain/applicant/enums/ApplicantStatus.java
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/CustomControllerAdvice.java
Labels: FEAT

#19 [infra] 서버 시간대 설정 추가
  Dockerfile
Labels: INFRA

#18 [fix] CORS 개방 설정
  src/main/java/dmu/dasom/api/global/auth/config/SecurityConfig.java
Labels: FIX

#25 [fix] Google 컨트롤러와 Google 서비스 간의 의존성 추가
  src/main/java/dmu/dasom/api/domain/google/service/GoogleApiService.java
  src/main/resources/application-credentials.yml
Labels: FIX

#22 [feat] 지원자 조회 API 구현
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantDetailsResponseDto.java
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantResponseDto.java
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantStatusUpdateRequestDto.java
  src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
  src/main/java/dmu/dasom/api/global/dto/PageResponse.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
Labels: FEAT

#30 [feat] 지원자 학번 중복 불가 설정
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantCreateRequestDto.java
  src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
Labels: FEAT

#36 [fix] 지원자 생성 요청 엔티티 변환 메소드 수정
  src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantCreateRequestDto.java
Labels: FIX

#37 [feat] 토큰 응답 시 사용자 권한 응답 추가
  src/main/java/dmu/dasom/api/domain/member/controller/MemberController.java
  src/main/java/dmu/dasom/api/domain/member/service/MemberServiceImpl.java
  src/main/java/dmu/dasom/api/global/auth/dto/TokenBox.java
  src/main/java/dmu/dasom/api/global/auth/filter/CustomAuthenticationFilter.java
  src/main/java/dmu/dasom/api/global/auth/jwt/JwtUtil.java
Labels: FEAT

#39 [feat] 메일 발송 기능 구현
  build.gradle
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/email/enums/MailType.java
  src/main/java/dmu/dasom/api/domain/email/service/EmailService.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
  src/main/resources/application-credentials.yml
  src/main/resources/template/email-template.html
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
  src/test/java/dmu/dasom/api/domain/email/EmailServiceTest.java
Labels: FEAT

#34 [feat] 다솜소식 API 구현
  src/main/java/dmu/dasom/api/domain/news/controller/NewsController.java
  src/main/java/dmu/dasom/api/domain/news/dto/NewsRequestDto.java
  src/main/java/dmu/dasom/api/domain/news/dto/NewsResponseDto.java
  src/main/java/dmu/dasom/api/domain/news/entity/NewsEntity.java
  src/main/java/dmu/dasom/api/domain/news/repository/NewsRepository.java
  src/main/java/dmu/dasom/api/domain/news/service/NewsService.java
  src/test/java/dmu/dasom/api/domain/news/NewsServiceTest.java
Labels: FEAT

#40 [feat] 모집 일정 관리 API 구현
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/domain/recruit/dto/RecruitConfigResponseDto.java
  src/main/java/dmu/dasom/api/domain/recruit/dto/RecruitScheduleModifyRequestDto.java
  src/main/java/dmu/dasom/api/domain/recruit/entity/Recruit.java
  src/main/java/dmu/dasom/api/domain/recruit/enums/ConfigKey.java
  src/main/java/dmu/dasom/api/domain/recruit/repository/RecruitRepository.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
  src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
Labels: FEAT

#44 [feat] 다솜소식 수정 삭제 명세서 추가
  src/main/java/dmu/dasom/api/domain/news/controller/NewsController.java
Labels: FEAT

#49 [feat] 메일 발송 기능 구현
  src/main/java/dmu/dasom/api/domain/email/service/EmailService.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
  src/main/resources/template/email-template.html
  src/main/resources/template/logo.png
  src/test/java/dmu/dasom/api/domain/email/EmailServiceTest.java
Labels: FEAT

#48 [feat] 합격 조회 API 구현
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/domain/recruit/dto/ResultCheckRequestDto.java
  src/main/java/dmu/dasom/api/domain/recruit/dto/ResultCheckResponseDto.java
  src/main/java/dmu/dasom/api/domain/recruit/enums/ResultCheckType.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
  src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
Labels: FEAT

#31 [feat] 지원자 API 와 구글 스프레드 시트 연동
  .gitignore
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
Labels: FEAT

#54 [infra] 무중단 배포 구성
  src/main/java/dmu/dasom/api/global/healthcheck/HealthCheck.java
Labels: INFRA
