Repository DASOM-GitHub/dasom-web-backend, pull requests merged in 2025-08, with the labels that each got.

#80 [refactor] 뉴스 전체 조회 로직 리팩토링
  src/main/java/dmu/dasom/api/domain/news/dto/NewsListResponseDto.java
  src/main/java/dmu/dasom/api/domain/news/entity/NewsEntity.java
Labels: REFACTOR

#68 [fix] 엔드포인트 접근 권한 수정
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
  src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
  src/main/java/dmu/dasom/api/domain/common/exception/CustomErrorController.java
  src/main/java/dmu/dasom/api/domain/google/controller/GoogleController.java
  src/main/java/dmu/dasom/api/domain/google/enums/MailType.java
  src/main/java/dmu/dasom/api/domain/google/service/EmailService.java
  src/main/java/dmu/dasom/api/domain/google/service/GoogleApiService.java
  src/main/java/dmu/dasom/api/domain/member/controller/MemberController.java
  src/main/java/dmu/dasom/api/domain/news/controller/NewsController.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminApplicantController.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminFileController.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminNewsController.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminRecruitController.java
  src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
  src/test/java/dmu/dasom/api/domain/email/EmailServiceTest.java
Labels: FIX

#97 [refactor] 이미지 저장 로직 수정
  build.gradle
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/global/R2/config/R2Config.java
  src/main/java/dmu/dasom/api/global/R2/service/R2Service.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminFileController.java
  src/main/java/dmu/dasom/api/global/file/dto/FileResponseDto.java
  src/main/java/dmu/dasom/api/global/file/entity/FileEntity.java
  src/main/java/dmu/dasom/api/global/file/service/FileService.java
  src/main/resources/application-credentials.yml
Labels: REFACTOR

#96 [Refactor] 기수 관리 추가 및 기존 기능과 연동
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/member/dto/SignupRequestDto.java
  src/main/java/dmu/dasom/api/domain/member/entity/Member.java
  src/main/java/dmu/dasom/api/domain/member/service/MemberServiceImpl.java
  src/main/java/dmu/dasom/api/domain/recruit/entity/Recruit.java
  src/main/java/dmu/dasom/api/domain/recruit/enums/ConfigKey.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/dmu/dasom/api/global/admin/controller/AdminRecruitController.java
  src/test/java/dmu/dasom/api/domain/member/MemberServiceTest.java
  src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
Labels: REFACTOR, FEAT, TEST

#93 [Refactor]면접 예약 날짜 변경 기능 추가
  src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
  src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
  src/main/java/dmu/dasom/api/domain/google/enums/MailType.java
  src/main/java/dmu/dasom/api/domain/google/service/EmailService.java
  src/main/java/dmu/dasom/api/domain/interview/controller/InterviewController.java
  src/main/java/dmu/dasom/api/domain/interview/dto/InterviewReservationModifyRequestDto.java
  src/main/java/dmu/dasom/api/domain/interview/dto/VerificationCodeRequestDto.java
  src/main/java/dmu/dasom/api/domain/interview/entity/InterviewReservation.java
  src/main/java/dmu/dasom/api/domain/interview/repository/InterviewReservationRepository.java
  src/main/java/dmu/dasom/api/domain/interview/repository/InterviewSlotRepository.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewService.java
  src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
  src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
  src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
  src/main/java/dmu/dasom/api/global/util/VerificationCodeManager.java
  src/main/resources/templates/verify-num-email.html
Labels: REFACTOR

#94 [Refactor] 로그인 로직 분리
  src/main/java/dmu/dasom/api/domain/member/controller/MemberController.java
  src/main/java/dmu/dasom/api/domain/member/dto/LoginRequestDto.java
  src/main/java/dmu/dasom/api/domain/member/service/MemberService.java
  src/main/java/dmu/dasom/api/domain/member/service/MemberServiceImpl.java
  src/main/java/dmu/dasom/api/global/auth/config/SecurityConfig.java
Labels: REFACTOR
